import { Style, StyleProperties } from './style';
export type WidthMeasurable = {
    width: number;
};
export type HeightMeasurable = {
    height: number;
};
export type SizeMeasurable = WidthMeasurable & HeightMeasurable;
export declare class Component {
    readonly id: string;
    rawX: number;
    rawY: number;
    rawWidth: number;
    rawHeight: number;
    contentWidth: number;
    contentHeight: number;
    protected readonly style: Style;
    constructor(id: string, style?: StyleProperties);
    get x(): number;
    get y(): number;
    get position(): "relative" | "absolute";
    get top(): number | undefined;
    get left(): number | undefined;
    get bottom(): number | undefined;
    get right(): number | undefined;
    get layout(): "flow" | "horizontalBox" | "verticalBox";
    get justifyContent(): "left" | "center" | "spaceBetween" | "right";
    get alignItems(): "center" | "spaceBetween" | "top" | "bottom";
    get breakAfter(): boolean;
    get visible(): boolean;
    get horizontalItemArrangement(): "real" | "ratio";
    get verticalItemArrangement(): "real" | "ratio";
    get paddingTop(): number;
    get paddingRight(): number;
    get paddingBottom(): number;
    get paddingLeft(): number;
    get width(): number;
    get height(): number;
    get layoutWidth(): number;
    get layoutHeight(): number;
    get marginTop(): number;
    get marginRight(): number;
    get marginBottom(): number;
    get marginLeft(): number;
    get horizontalMargin(): number;
    offsetLeft(parent: Component): number;
    offsetRight(parent: Component): number;
    horizontalOffset(parent: Component): number;
    testIfComponent(obj: unknown): obj is Component;
    get verticalMargin(): number;
    offsetTop(parent: Component): number;
    offsetBottom(parent: Component): number;
    verticalOffset(parent: Component): number;
    innerWidth(parent: Component | WidthMeasurable): number;
    innerHeight(parent: Component | HeightMeasurable): number;
    relayout(ox: number | undefined, oy: number | undefined, parent: Component | SizeMeasurable): void;
    move(toX: number, toY: number, parent: SizeMeasurable): void;
    resize(parent: Component | SizeMeasurable): void;
    private moveX;
    private moveY;
}
